### ISSUE TITLE
Feature - Participant Interface - Submit the graph

### ISSUE THREAD

**Issue by LKBEAST** [2022-CITS3200-GraphTeam/CITS3200-GroupProject#12]
**USER STORY**

As a Participant 
I want to submit my graph details to Qualtrics.
So that I can save my actions and move onto the next question. 

**ACCEPTANCE CRITERIA**

- [ ] _Participant clicks on submit button when constraint not met_
 Given I finished adjusting the graph
When I click on the grey submit button when the constraints are not met 
Then the graph cannot be submitted yet  

- [ ] _Participant clicks on submit button when constraints are all met_ 
Given I finished adjusting the graph 
When I click on the blue submit button 
Then the current graph is saved and the next one is displayed 

- [ ] _Results are saved to Qualtrics_
Given I have pressed the submit button 
When the Qualtrics admin checks the answers
Then the graph details should be visible

![Image](https://user-images.githubusercontent.com/83956440/186301140-56a511ae-5d9d-4618-a2cd-048715138b8b.png)

**Comment by met4000** [comment]
Closed by #88
