### ISSUE TITLE
Preparing team session for Story and Acceptance Criteria writing

### ISSUE THREAD

**Issue by DannaTB** [2022-CITS3200-GraphTeam/CITS3200-GroupProject#5]
Deliverable 5 - Organising a session for Wednesday 10/08/2022 9.30 am - 11  am to walk through Story and Acceptance Criteria writing for our product requirements.

Aiming to dedicate 2 hours to organise our team session then we'll walk through it together on the agreed Wednesday session, followed up by either finalising these during the session or break up the deliverable further.

Potentially linked to Deliverable 4 - Acceptance Tests (this Deliverable requires a focus lead, needs re-assigning to someone with capacity so posted on team chat, requires actioning)

**Comment by met4000** [comment]
can this be closed as completed?

**Comment by DannaTB** [comment]
Yes, I think we're all sufficiently-versed in story and acceptance criteria writing now haha
