### ISSUE TITLE
Functionality - Total Sum button

### ISSUE THREAD

**Issue by blakegeelen** [2022-CITS3200-GraphTeam/CITS3200-GroupProject#67]
Add functionality to the total sum button by using the same strategy used on the rules section

**Comment by met4000** [comment]
Implemented by #79 , however there is a bug with the drag functionality not triggering `updateGraph()` and hence not updating the total sum value

**Comment by met4000** [comment]
Implementation method changed due to client feedback; preventing graph submission when invalid, and providing feedback to the user on e.g. the current and required sum for the graph.
